name: clinic_appointments
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-104.0.dev

dependencies:
  cloud_firestore: ^5.6.5
  crypto: ^3.0.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
