import '../../features/appointment_slot/models/appointment_slot.dart';
import '../../features/appointment/models/appointment.dart';
import '../../features/doctor/models/doctor.dart';
import '../../features/patient/models/patient.dart';

List<Doctor> mockDoctors = [
  Doctor(
    id: 'D1',
    name: 'Dr. Ahmed Ali',
    specialty: 'General Practitioner',
    phoneNumber: '+96512345678',
    email: 'ahmed@example.com',
    imageUrl:
        'https://www.nvisioncenters.com/wp-content/uploads/types-of-eye-care-professionals.jpg',
    isAvailable: true,
    socialMedia: {'facebook': 'url', 'instagram': 'url'},
    bio:
        'Dr. Ahmed Ali is a dedicated General Practitioner with over 15 years of experience in providing comprehensive healthcare.',
  ),
  Doctor(
      id: 'D2',
      name: 'Dr. Fatima Al-Sabah',
      specialty: 'Pediatrician',
      phoneNumber: '+96587654321',
      email: 'fatima.alsabah@example.com',
      imageUrl:
          'https://mytpmg.com/wp-content/uploads/2021/02/eyedoctor-360-x-240.jpg',
      isAvailable: true,
      socialMedia: {'facebook': 'url', 'instagram': 'url'}),
  Doctor(
    id: 'D3',
    name: 'Dr. Khalid Al-Mutairi',
    specialty: 'Cardiologist',
    phoneNumber: '+96523456789',
    email: 'khalid.almutairi@example.com',
    imageUrl: '',
    isAvailable: false,
  ),
];

// Define appointment IDs first for reference
const appointmentIds = ['A1', 'A3', 'A4', 'A5'];

List<Patient> mockPatients = [
  Patient(
    id: '1',
    name: 'John Doe',
    phone: '62228494',
    email: 'john.doe@email.com',
    address: '123 Main St, Kuwait City',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1985, 5, 15),
    registeredAt: DateTime(2025, 1, 10),
    status: PatientStatus.active,
    notes: 'Regular check-ups required',
    appointmentIds: ['A1'], // Track appointments for this patient
  ),
  Patient(
    id: '2',
    name: 'Jane Smith',
    phone: '+96523456789',
    email: 'jane.smith@email.com',
    address: '45 Gulf Road, Salmiya',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1990, 8, 22),
    registeredAt: DateTime(2025, 1, 12),
    status: PatientStatus.active,
    appointmentIds: [], // No appointments yet
  ),
  Patient(
    id: '3',
    name: 'Ali Hassan',
    phone: '+96534567890',
    email: 'ali.hassan@email.com',
    address: '12 Arabian Gulf St, Hawally',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1978, 3, 10),
    registeredAt: DateTime(2025, 2, 5),
    status: PatientStatus.active,
    notes: 'Allergic to penicillin',
    appointmentIds: ['A3'], // Track appointments for this patient
  ),
  Patient(
    id: '4',
    name: 'Sara Ahmed',
    phone: '+96545678901',
    email: 'sara.ahmed@email.com',
    address: '78 Salem Al Mubarak St, Salmiya',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1995, 12, 1),
    registeredAt: DateTime(2025, 2, 10),
    status: PatientStatus.active,
    appointmentIds: ['A4'], // Track appointments for this patient
  ),
  Patient(
    id: '5',
    name: 'Michael Lee',
    phone: '+96556789012',
    email: 'michael.lee@email.com',
    address: '23 Fahad Al Salem St, Qibla',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1988, 7, 18),
    registeredAt: DateTime(2025, 2, 15),
    status: PatientStatus.inactive,
    notes: 'Moved to another city',
    appointmentIds: ['A5'], // Track appointments for this patient
  ),
  Patient(
    id: '6',
    name: 'Fatima Noor',
    phone: '+96567890123',
    email: 'fatima.noor@email.com',
    address: '56 Shuwaikh Residential',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1992, 9, 5),
    registeredAt: DateTime(2025, 3, 1),
    status: PatientStatus.active,
    appointmentIds: [], // No appointments yet
  ),
  Patient(
    id: '7',
    name: 'Omar Abdullah',
    phone: '+96578901234',
    email: 'omar.abdullah@email.com',
    address: '89 Al-Rashid St, Fahaheel',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1980, 11, 30),
    registeredAt: DateTime(2025, 3, 8),
    status: PatientStatus.active,
    notes: 'Requires monthly follow-up',
    appointmentIds: [], // No appointments yet
  ),
  Patient(
    id: '8',
    name: 'Linda Wong',
    phone: '+96589012345',
    email: 'linda.wong@email.com',
    address: '34 Al-Mutawakel St, Sharq',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1987, 4, 25),
    registeredAt: DateTime(2025, 3, 15),
    status: PatientStatus.active,
    appointmentIds: [], // No appointments yet
  ),
  Patient(
    id: '9',
    name: 'David Kim',
    phone: '+96590123456',
    email: 'david.kim@email.com',
    address: '67 Al-Shuhada St, Dasman',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1993, 6, 12),
    registeredAt: DateTime(2025, 3, 20),
    status: PatientStatus.active,
    appointmentIds: [], // No appointments yet
  ),
  Patient(
    id: '10',
    name: 'Sophia Al-Farsi',
    phone: '+96512349876',
    email: 'sophia.alfarsi@email.com',
    address: '15 Al-Soor St, Mirqab',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1989, 2, 8),
    registeredAt: DateTime(2025, 3, 25),
    status: PatientStatus.active,
    notes: 'Emergency contact available',
    appointmentIds: [], // No appointments yet
  ),
];

List<Appointment> mockAppointments = [
  Appointment(
      id: 'A1',
      patientId: mockPatients[0].id,
      doctorId: mockDoctors[0].id,
      appointmentSlotId: '1',
      dateTime: DateTime(2025, 2, 7),
      status: 'scheduled',
      paymentStatus: 'unpaid'),
  Appointment(
      id: 'A3',
      patientId: mockPatients[2].id,
      doctorId: mockDoctors[0].id,
      appointmentSlotId: '4',
      dateTime: DateTime(2025, 2, 28),
      status: 'scheduled',
      paymentStatus: 'unpaid'),
  Appointment(
      id: 'A4',
      patientId: mockPatients[3].id,
      doctorId: mockDoctors[0].id,
      appointmentSlotId: '1',
      dateTime: DateTime(2025, 2, 7),
      status: 'scheduled',
      paymentStatus: 'paid'),
  Appointment(
      id: 'A5',
      patientId: mockPatients[4].id,
      doctorId: mockDoctors[0].id,
      appointmentSlotId: '3',
      dateTime: DateTime(2025, 03, 25),
      status: 'completed',
      paymentStatus: 'paid'),
];

// Additional appointment slots
List<AppointmentSlot> mockAppointmentSlots = [
  AppointmentSlot(
    id: '1',
    doctorId: 'D1',
    date: DateTime(2025, 02, 07),
    maxPatients: 7,
    bookedPatients: 2,
    appointmentIds: ['A1', 'A4'],
  ),
  AppointmentSlot(
    id: '2',
    doctorId: 'D2',
    date: DateTime(2025, 03, 01),
    maxPatients: 8,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  AppointmentSlot(
    id: '3',
    doctorId: 'D1',
    date: DateTime(2025, 03, 25),
    maxPatients: 12,
    bookedPatients: 1,
    appointmentIds: ['A5'],
  ),
  AppointmentSlot(
    id: '4',
    doctorId: 'D1',
    date: DateTime(2025, 02, 28),
    maxPatients: 6,
    bookedPatients: 1,
    appointmentIds: ['A3'],
  ),
  AppointmentSlot(
    id: '5',
    doctorId: 'D2',
    date: DateTime(2025, 02, 28),
    maxPatients: 10,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  AppointmentSlot(
    id: '6',
    doctorId: 'D2',
    date: DateTime(2025, 04, 17),
    maxPatients: 10,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  // Additional appointment slots
  AppointmentSlot(
    id: '7',
    doctorId: 'D3',
    date: DateTime(2025, 03, 15),
    maxPatients: 8,
    bookedPatients: 2,
    appointmentIds: ['A6', 'A7'],
  ),
  AppointmentSlot(
    id: '8',
    doctorId: 'D1',
    date: DateTime(2025, 03, 10),
    maxPatients: 10,
    bookedPatients: 3,
    appointmentIds: ['A8', 'A9', 'A10'],
  ),
  AppointmentSlot(
    id: '9',
    doctorId: 'D2',
    date: DateTime(2025, 03, 12),
    maxPatients: 6,
    bookedPatients: 1,
    appointmentIds: ['A11'],
  ),
  AppointmentSlot(
    id: '10',
    doctorId: 'D3',
    date: DateTime(2025, 04, 05),
    maxPatients: 7,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  AppointmentSlot(
    id: '11',
    doctorId: 'D1',
    date: DateTime(2025, 04, 12),
    maxPatients: 9,
    bookedPatients: 1,
    appointmentIds: ['A12'],
  ),
  AppointmentSlot(
    id: '12',
    doctorId: 'D2',
    date: DateTime(2025, 04, 20),
    maxPatients: 8,
    bookedPatients: 2,
    appointmentIds: ['A13', 'A14'],
  ),
  AppointmentSlot(
    id: '13',
    doctorId: 'D3',
    date: DateTime(2025, 04, 25),
    maxPatients: 5,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  AppointmentSlot(
    id: '14',
    doctorId: 'D1',
    date: DateTime(2025, 05, 03),
    maxPatients: 10,
    bookedPatients: 0,
    appointmentIds: [],
  ),
  AppointmentSlot(
    id: '15',
    doctorId: 'D2',
    date: DateTime(2025, 05, 10),
    maxPatients: 8,
    bookedPatients: 0,
    appointmentIds: [],
  ),
];

// Additional doctors
List<Doctor> additionalDoctors = [
  Doctor(
    id: 'D4',
    name: 'Dr. Sarah Johnson',
    specialty: 'Ophthalmologist',
    phoneNumber: '+96512398765',
    email: 'sarah.johnson@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww',
    isAvailable: true,
    socialMedia: {'twitter': 'url', 'linkedin': 'url'},
    bio: 'Dr. Sarah Johnson is a board-certified ophthalmologist specializing in retinal diseases.',
  ),
  Doctor(
    id: 'D5',
    name: 'Dr. Mohammed Al-Rashid',
    specialty: 'Neurologist',
    phoneNumber: '+96523789456',
    email: 'mohammed.alrashid@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8ZG9jdG9yfGVufDB8fDB8fHww',
    isAvailable: true,
    bio: 'Dr. Mohammed Al-Rashid has over 20 years of experience in neurology.',
  ),
  Doctor(
    id: 'D6',
    name: 'Dr. Layla Hassan',
    specialty: 'Dermatologist',
    phoneNumber: '+96534567123',
    email: 'layla.hassan@example.com',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661580574627-9211124e5c3f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZG9jdG9yfGVufDB8fDB8fHww',
    isAvailable: false,
    socialMedia: {'instagram': 'url'},
    bio: 'Dr. Layla Hassan specializes in cosmetic and medical dermatology.',
  ),
  Doctor(
    id: 'D7',
    name: 'Dr. Robert Chen',
    specialty: 'Endocrinologist',
    phoneNumber: '+96545678234',
    email: 'robert.chen@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGRvY3RvcnxlbnwwfHwwfHx8MA%3D%3D',
    isAvailable: true,
    bio: 'Dr. Robert Chen specializes in diabetes and thyroid disorders.',
  ),
  Doctor(
    id: 'D8',
    name: 'Dr. Aisha Al-Qasim',
    specialty: 'Gynecologist',
    phoneNumber: '+96556789345',
    email: 'aisha.alqasim@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGRvY3RvcnxlbnwwfHwwfHx8MA%3D%3D',
    isAvailable: true,
    socialMedia: {'facebook': 'url', 'twitter': 'url'},
    bio: 'Dr. Aisha Al-Qasim is passionate about women\'s health and preventive care.',
  ),
];

// Additional patients
List<Patient> additionalPatients = [
  Patient(
    id: '11',
    name: 'Hamad Al-Khaled',
    phone: '+96567123456',
    email: 'hamad.alkhaled@email.com',
    address: '25 Jabriya St, Kuwait City',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1979, 6, 14),
    registeredAt: DateTime(2025, 2, 5),
    status: PatientStatus.active,
    appointmentIds: ['A6'],
  ),
  Patient(
    id: '12',
    name: 'Mariam Al-Sayed',
    phone: '+96578234567',
    email: 'mariam.alsayed@email.com',
    address: '76 Riggae St, Kuwait',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1998, 11, 21),
    registeredAt: DateTime(2025, 2, 10),
    status: PatientStatus.active,
    notes: 'Pregnant - due in July 2025',
    appointmentIds: ['A7'],
  ),
  Patient(
    id: '13',
    name: 'Abdul Rahman',
    phone: '+96589345678',
    email: 'abdul.rahman@email.com',
    address: '43 Farwaniya St, Kuwait',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1972, 3, 5),
    registeredAt: DateTime(2025, 2, 15),
    status: PatientStatus.active,
    notes: 'Diabetic patient',
    appointmentIds: ['A8'],
  ),
  Patient(
    id: '14',
    name: 'Noor Al-Ibrahim',
    phone: '+96590456789',
    email: 'noor.alibrahim@email.com',
    address: '12 Khaitan St, Kuwait',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1990, 9, 18),
    registeredAt: DateTime(2025, 2, 20),
    status: PatientStatus.active,
    appointmentIds: ['A9'],
  ),
  Patient(
    id: '15',
    name: 'Yousef Al-Mansour',
    phone: '+96521567890',
    email: 'yousef.almansour@email.com',
    address: '65 Jahra St, Kuwait',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1985, 1, 10),
    registeredAt: DateTime(2025, 2, 25),
    status: PatientStatus.inactive,
    notes: 'Temporarily relocated abroad',
    appointmentIds: ['A10'],
  ),
  Patient(
    id: '16',
    name: 'Fatima Al-Mutairi',
    phone: '+96532678901',
    email: 'fatima.almutairi@email.com',
    address: '31 Sabah Al-Salem St, Kuwait',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1994, 5, 30),
    registeredAt: DateTime(2025, 3, 5),
    status: PatientStatus.active,
    appointmentIds: ['A11'],
  ),
  Patient(
    id: '17',
    name: 'Khalid Al-Sabah',
    phone: '+96543789012',
    email: 'khalid.alsabah@email.com',
    address: '54 Abdullah Al-Salem St, Kuwait',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1975, 7, 25),
    registeredAt: DateTime(2025, 3, 10),
    status: PatientStatus.active,
    notes: 'Heart condition - requires regular follow-ups',
    appointmentIds: ['A12'],
  ),
  Patient(
    id: '18',
    name: 'Zainab Al-Ali',
    phone: '+96554890123',
    email: 'zainab.alali@email.com',
    address: '87 Sabah Al-Ahmad St, Kuwait',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1982, 12, 14),
    registeredAt: DateTime(2025, 3, 15),
    status: PatientStatus.active,
    appointmentIds: ['A13'],
  ),
  Patient(
    id: '19',
    name: 'Hassan Al-Jaber',
    phone: '+96565901234',
    email: 'hassan.aljaber@email.com',
    address: '23 Mubarak Al-Kabeer St, Kuwait',
    gender: PatientGender.male,
    dateOfBirth: DateTime(1967, 4, 9),
    registeredAt: DateTime(2025, 3, 20),
    status: PatientStatus.active,
    appointmentIds: ['A14'],
  ),
  Patient(
    id: '20',
    name: 'Noura Al-Ajmi',
    phone: '+96576012345',
    email: 'noura.alajmi@email.com',
    address: '42 Hawally St, Kuwait',
    gender: PatientGender.female,
    dateOfBirth: DateTime(1997, 8, 3),
    registeredAt: DateTime(2025, 3, 25),
    status: PatientStatus.active,
    notes: 'Allergic to penicillin and sulfa drugs',
    appointmentIds: [],
  ),
];

// Additional appointments
List<Appointment> additionalAppointments = [
  Appointment(
    id: 'A6',
    patientId: '11',
    doctorId: 'D3',
    appointmentSlotId: '7',
    dateTime: DateTime(2025, 3, 15, 9, 0),
    status: 'scheduled',
    paymentStatus: 'unpaid',
  ),
  Appointment(
    id: 'A7',
    patientId: '12',
    doctorId: 'D3',
    appointmentSlotId: '7',
    dateTime: DateTime(2025, 3, 15, 10, 30),
    status: 'scheduled',
    paymentStatus: 'paid',
  ),
  Appointment(
    id: 'A8',
    patientId: '13',
    doctorId: 'D1',
    appointmentSlotId: '8',
    dateTime: DateTime(2025, 3, 10, 9, 0),
    status: 'scheduled',
    paymentStatus: 'unpaid',
    notes: 'Follow-up for diabetes management',
  ),
  Appointment(
    id: 'A9',
    patientId: '14',
    doctorId: 'D1',
    appointmentSlotId: '8',
    dateTime: DateTime(2025, 3, 10, 10, 30),
    status: 'scheduled',
    paymentStatus: 'paid',
  ),
  Appointment(
    id: 'A10',
    patientId: '15',
    doctorId: 'D1',
    appointmentSlotId: '8',
    dateTime: DateTime(2025, 3, 10, 14, 0),
    status: 'cancelled',
    paymentStatus: 'refunded',
    notes: 'Patient relocated abroad',
  ),
  Appointment(
    id: 'A11',
    patientId: '16',
    doctorId: 'D2',
    appointmentSlotId: '9',
    dateTime: DateTime(2025, 3, 12, 11, 0),
    status: 'scheduled',
    paymentStatus: 'unpaid',
  ),
  Appointment(
    id: 'A12',
    patientId: '17',
    doctorId: 'D1',
    appointmentSlotId: '11',
    dateTime: DateTime(2025, 4, 12, 9, 30),
    status: 'scheduled',
    paymentStatus: 'unpaid',
    notes: 'Regular cardiac check-up',
  ),
  Appointment(
    id: 'A13',
    patientId: '18',
    doctorId: 'D2',
    appointmentSlotId: '12',
    dateTime: DateTime(2025, 4, 20, 10, 0),
    status: 'scheduled',
    paymentStatus: 'paid',
  ),
  Appointment(
    id: 'A14',
    patientId: '19',
    doctorId: 'D2',
    appointmentSlotId: '12',
    dateTime: DateTime(2025, 4, 20, 11, 30),
    status: 'scheduled',
    paymentStatus: 'unpaid',
  ),
];

// Combining mock data with additional data
final allDoctors = [...mockDoctors, ...additionalDoctors];
final allPatients = [...mockPatients, ...additionalPatients];
final allAppointments = [...mockAppointments, ...additionalAppointments];
// Note: mockAppointmentSlots already includes all the slots

// Additional mock data for future Firebase integration
final firebaseConfig = {
  'apiKey': 'your-api-key',
  'authDomain': 'clinic-app.firebaseapp.com',
  'projectId': 'clinic-app',
  'storageBucket': 'clinic-app.appspot.com',
  'messagingSenderId': '123456789012',
  'appId': '1:123456789012:web:abc123def456',
};

// Clinic configuration data
final clinicConfig = {
  'name': 'Kuwait Medical Center',
  'address': 'Block 5, Street 10, Building 3, Kuwait City',
  'phone': '+965 2222-3333',
  'email': 'info@kuwaitmedical.com',
  'website': 'www.kuwaitmedicalcenter.com',
  'workingHours': {
    'Sunday': '08:00 - 20:00',
    'Monday': '08:00 - 20:00',
    'Tuesday': '08:00 - 20:00',
    'Wednesday': '08:00 - 20:00',
    'Thursday': '08:00 - 16:00',
    'Friday': 'Closed',
    'Saturday': '10:00 - 16:00',
  },
  'services': [
    'General Medicine',
    'Pediatrics',
    'Cardiology',
    'Ophthalmology',
    'Neurology',
    'Dermatology',
    'Endocrinology',
    'Gynecology',
  ],
  'insuranceAccepted': [
    'Kuwait Health Insurance',
    'GIG Health',
    'Boubyan Takaful',
    'Warba Insurance',
    'Gulf Insurance Group',
  ],
};