// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--r0clFPbuHNknPeO_wpyi8GI05hUpPU',
    appId: '1:948470235864:web:da44679378d0c8451e4dad',
    messagingSenderId: '948470235864',
    projectId: 'eye-clinic-41214',
    authDomain: 'eye-clinic-41214.firebaseapp.com',
    storageBucket: 'eye-clinic-41214.firebasestorage.app',
    measurementId: 'G-WX7JVGCFE3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC--r0clFPbuHNknPeO_wpyi8GI05hUpPU',
    appId: '1:948470235864:web:b5dfa304c285c1a01e4dad',
    messagingSenderId: '948470235864',
    projectId: 'eye-clinic-41214',
    authDomain: 'eye-clinic-41214.firebaseapp.com',
    storageBucket: 'eye-clinic-41214.firebasestorage.app',
    measurementId: 'G-TJV0S2ME71',
  );
}
